version: "0.2"

services:
  kafka:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_CREATE_TOPICS: stock-prices:3:1:retention.ms=5000,cleanup.policy=delete,segment.bytes=1048576

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  authenticationservice:
    build:
      context: ./authenticationservice
      dockerfile: Dockerfile
    container_name: authenticationservice
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka
      - redis
      - portfolioservice
  transactionservice:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    container_name: transactionservice
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - kafka
      - redis
      - portfolioservice
  portfolioservice:
    build:
      context: ./portfolio-service
      dockerfile: Dockerfile
    container_name: portfolioservice
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - kafka
      - redis
volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
