global:
  imagePullPolicy: IfNotPresent

services:
  authentication:
    image: theboringproject-authenticationservice:latest
    port: 8081
    nodePort: 30081
  portfolio:
    image: theboringproject-portfolioservice:latest
    port: 8082
    nodePort: 30082
  transaction:
    image: theboringproject-transactionservice:latest
    port: 8083
    nodePort: 30083

postgres:
  image: postgres:15
  user: admin
  password: admin
  db: portfolio_db

redis:
  image: redis:7

kafka:
  image: apache/kafka:3.7.0
